// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0FloOyZyoAR2FaF9T4N4E-SJiwqaT-Ik',
    appId: '1:203376393327:web:2890852add0ba1da7fe19a',
    messagingSenderId: '203376393327',
    projectId: 'chat-2024-d551d',
    authDomain: 'chat-2024-d551d.firebaseapp.com',
    storageBucket: 'chat-2024-d551d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYl-H49NRjARrx2ABFtg1kGmCsBIWMreM',
    appId: '1:203376393327:android:62fd8889e0541b7d7fe19a',
    messagingSenderId: '203376393327',
    projectId: 'chat-2024-d551d',
    storageBucket: 'chat-2024-d551d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjXvN2IWPhAo5HIzWaSO-4y-H9I9-aIOY',
    appId: '1:203376393327:ios:91e12b4ab3fe94617fe19a',
    messagingSenderId: '203376393327',
    projectId: 'chat-2024-d551d',
    storageBucket: 'chat-2024-d551d.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjXvN2IWPhAo5HIzWaSO-4y-H9I9-aIOY',
    appId: '1:203376393327:ios:91e12b4ab3fe94617fe19a',
    messagingSenderId: '203376393327',
    projectId: 'chat-2024-d551d',
    storageBucket: 'chat-2024-d551d.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0FloOyZyoAR2FaF9T4N4E-SJiwqaT-Ik',
    appId: '1:203376393327:web:168d8e5093aec6497fe19a',
    messagingSenderId: '203376393327',
    projectId: 'chat-2024-d551d',
    authDomain: 'chat-2024-d551d.firebaseapp.com',
    storageBucket: 'chat-2024-d551d.firebasestorage.app',
  );
}
